### ISSUE TITLE
Unable to install the package via npm

### ISSUE THREAD

**Issue by clemblanco** [amitkothari/ti-installr-hook#5]
This is what I get when I try to run `sudo npm install -g ti-installr-hook --unsafe-perm`:

```
npm WARN deprecated node-uuid@1.4.7: Use uuid module instead
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated uglify-js@2.8.14: Significant regressions found
/Users/clement/.n/bin/ti-installr-hook -> /Users/clement/.n/lib/node_modules/ti-installr-hook/bin/install

> ti-installr-hook@0.4.0 postinstall /Users/clement/.n/lib/node_modules/ti-installr-hook
> node bin/install

events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: spawn ti ENOENT
    at exports._errnoException (util.js:1034:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/clement/.n/bin/node" "/Users/clement/.n/bin/npm" "install" "-g" "ti-installr-hook" "--unsafe-perm"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! ti-installr-hook@0.4.0 postinstall: `node bin/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ti-installr-hook@0.4.0 postinstall script 'node bin/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ti-installr-hook package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ti-installr-hook
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ti-installr-hook
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/clement/.npm/_logs/2017-03-30T16_04_14_272Z-debug.log
```

Here is the log file `/Users/clement/.npm/_logs/2017-03-30T16_04_14_272Z-debug.log`.

[2017-03-30T16_04_14_272Z-debug.log.txt](https://github.com/amitkothari/ti-installr-hook/files/883053/2017-03-30T16_04_14_272Z-debug.log.txt)

`node -v` outputs `v7.8.0`
`npm -v` outputs `4.2.0`

**Comment by amitkothari** [comment]
Hi @Claymm, can you please run this command and see if it works on your machine.

ti config -a paths.hooks

I don't use Titanium any more that is why the repository is not maintained/updated, but with node v7.8.0 and npm v4.2.0, I can install the package successfully.

I am using Titanium CLI v5.0.12

**Comment by clemblanco** [comment]
```
$ node -v
v4.6.0
$ npm -v
2.15.9
$ appc ti config -a paths.hooks
Appcelerator Command-Line Interface, version 6.1.0
Copyright (c) 2014-2017, Appcelerator, Inc.  All Rights Reserved.

/Applications/Appcelerator Studio/plugins/com.appcelerator.titanium.liveview.core_1.1.0.1476939755/node_modules/liveview/hook
```
